laser:
  wavelength: 532 nm
  one_over_e_diameter: 2 cm
grid:
  x:
    min: 0 cm
    max: $(2*${/laser/one_over_e_diameter})
    N: $( (${max}-${min}).magnitude*100 )
  y:
    min: $(${../x/min})
    max: $(${../x/max})
    N: $(${../z/N})
